# from https://gitlab.com/pages/sphinx/-/blob/master/.gitlab-ci.yml
image: python:3.7-alpine

test:
  stage: test
  script:
  - pip install -U sphinx
  - sphinx-build -b html docs/source public
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
    
pages:
  stage: deploy
  script:
  - export PATH=$PATH:/home/gitlab-runner/.local/bin
  - python -m pip install --upgrade pip
  - python -m pip install --upgrade pillow
  - pip3 install sphinx sphinx_rtd_theme
  - pip3 install -r requirements.txt
  - pip3 install -e .
  - pip3 install -U sphinx
  - sphinx-build -b html docs/source public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
