name: CI test
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  testbuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Setup Python"
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: "Build"
      run: |
        pip install -r requirements.txt
        pip install -e .

    - name: "Run tests"
      run: |
        pytest tests/
