

name: Deploy
on:
  push:
    branches: [main]

jobs:
  docs:
    name: Generate Website
    runs-on: ubuntu-latest
    env:
      SPHINX_GITHUB_CHANGELOG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
 
      - name: setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.pages }}
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install .
        
      - name: Build
        run: sphinx-build -b dirhtml -v docs/source build

      - name: Upload to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/